trigger:
  batch: true
  branches:
    include:
      - "*"

workspace:
    clean: all

variables:
  - group: "ESFA - SonarCloud"
  - name: buildConfiguration
    value: 'release'

pool:
  name: DAS - Continuous Integration Agents
  demands: LATEST_DOTNET_VERSION -equals 3.1

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.10
    endpoint: SkillsFundingAgency

steps:
- template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

- template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
  parameters:
    SonarCloud: true
    SonarCloudProjectKey: SkillsFundingAgency_das-assessor-functions

- template: azure-pipelines-templates/build/step/dependency-check.yml@das-platform-building-blocks

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src/SFA.DAS.Assessor.Functions/SFA.DAS.Assessor.Functions.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) --no-restore --no-build'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
  inputs:
    Contents: 'azure/**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
