trigger:
  batch: true
  branches:
    include:
      - "master"

variables:
  - name: buildConfiguration
    value: 'release'

resources:
  repositories:
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/heads/DASD-13265
    endpoint: SkillsFundingAgency

stages:
- stage: Build
  jobs:
  - template: pipeline-templates/job/code-build.yml
